overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  esbuild: true
