/* tslint:disable */
/* eslint-disable */
/**
 * MONEI API v1
 * The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.
 *
 * The version of the OpenAPI document: 1.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type {SubscriptionPaymentMethods} from './subscription-payment-methods';

/**
 *
 * @export
 * @interface ActivateSubscriptionRequest
 */
export interface ActivateSubscriptionRequest {
  /**
   * A payment token generated by monei.js [Components](https://docs.monei.com/monei-js/overview/) or a paymentToken [saved after a previous successful payment](https://docs.monei.com/guides/save-payment-method/). In case of the first one, you will also need to send the `sessionId` used to generate the token in the first place.
   * @type {string}
   * @memberof ActivateSubscriptionRequest
   */
  paymentToken?: string;
  /**
   * A unique identifier within your system that adds security to the payment process. You need to pass the same session ID as the one used on the frontend to initialize MONEI Component (if you needed to). This is required if a payment token (not permanent) was already generated in the frontend.
   * @type {string}
   * @memberof ActivateSubscriptionRequest
   */
  sessionId?: string;
  /**
   * The amount to be added to the subscription\'s initial payment. A positive integer representing how much to charge in the smallest currency unit (e.g., 100 cents to charge 1.00 USD).
   * @type {number}
   * @memberof ActivateSubscriptionRequest
   */
  addAmount?: number;
  /**
   *
   * @type {SubscriptionPaymentMethods}
   * @memberof ActivateSubscriptionRequest
   */
  allowedPaymentMethods?: SubscriptionPaymentMethods;
  /**
   * A permanent identifier that refers to the initial payment of a sequence of payments. This value needs to be sent in the path for `RECURRING` payments.
   * @type {string}
   * @memberof ActivateSubscriptionRequest
   */
  sequenceId?: string;
  /**
   * The URL the customer will be directed to after transaction completed (successful or failed - except if `failUrl` is provided).
   * @type {string}
   * @memberof ActivateSubscriptionRequest
   */
  completeUrl?: string;
  /**
   * The URL the customer will be directed to after transaction has failed, instead of `completeUrl` (used in hosted payment page). This allows to provide two different URLs for successful and failed payments.
   * @type {string}
   * @memberof ActivateSubscriptionRequest
   */
  failUrl?: string;
  /**
   * The URL the customer will be directed to if they decide to cancel payment and return to your website (used in hosted payment page).
   * @type {string}
   * @memberof ActivateSubscriptionRequest
   */
  cancelUrl?: string;
  /**
   * A set of key-value pairs that you can attach to a resource. This can be useful for storing additional information about the resource in a structured format.
   * @type {object}
   * @memberof ActivateSubscriptionRequest
   */
  metadata?: object;
}
