/* tslint:disable */
/* eslint-disable */
/**
 * MONEI API v1
 * The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.
 *
 * The version of the OpenAPI document: 1.8.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataAlipay} from './payment-methods-metadata-alipay';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataApplePay} from './payment-methods-metadata-apple-pay';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataBancontact} from './payment-methods-metadata-bancontact';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataBizum} from './payment-methods-metadata-bizum';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataBlik} from './payment-methods-metadata-blik';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataCard} from './payment-methods-metadata-card';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataClickToPay} from './payment-methods-metadata-click-to-pay';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataEps} from './payment-methods-metadata-eps';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataGiropay} from './payment-methods-metadata-giropay';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataGooglePay} from './payment-methods-metadata-google-pay';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataIDeal} from './payment-methods-metadata-ideal';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataKlarna} from './payment-methods-metadata-klarna';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataMbway} from './payment-methods-metadata-mbway';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataSepa} from './payment-methods-metadata-sepa';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataSofort} from './payment-methods-metadata-sofort';
// May contain unused imports in some cases
// @ts-ignore
import type {PaymentMethodsMetadataTrustly} from './payment-methods-metadata-trustly';

/**
 * Additional configuration details for each payment method.
 * @export
 * @interface PaymentMethodsMetadata
 */
export interface PaymentMethodsMetadata {
  /**
   *
   * @type {PaymentMethodsMetadataAlipay}
   * @memberof PaymentMethodsMetadata
   */
  alipay?: PaymentMethodsMetadataAlipay;
  /**
   *
   * @type {PaymentMethodsMetadataBancontact}
   * @memberof PaymentMethodsMetadata
   */
  bancontact?: PaymentMethodsMetadataBancontact;
  /**
   *
   * @type {PaymentMethodsMetadataBizum}
   * @memberof PaymentMethodsMetadata
   */
  bizum?: PaymentMethodsMetadataBizum;
  /**
   *
   * @type {PaymentMethodsMetadataBlik}
   * @memberof PaymentMethodsMetadata
   */
  blik?: PaymentMethodsMetadataBlik;
  /**
   *
   * @type {PaymentMethodsMetadataCard}
   * @memberof PaymentMethodsMetadata
   */
  card?: PaymentMethodsMetadataCard;
  /**
   *
   * @type {PaymentMethodsMetadataEps}
   * @memberof PaymentMethodsMetadata
   */
  eps?: PaymentMethodsMetadataEps;
  /**
   *
   * @type {PaymentMethodsMetadataIDeal}
   * @memberof PaymentMethodsMetadata
   */
  iDeal?: PaymentMethodsMetadataIDeal;
  /**
   *
   * @type {PaymentMethodsMetadataMbway}
   * @memberof PaymentMethodsMetadata
   */
  mbway?: PaymentMethodsMetadataMbway;
  /**
   *
   * @type {PaymentMethodsMetadataMbway}
   * @memberof PaymentMethodsMetadata
   */
  multibanco?: PaymentMethodsMetadataMbway;
  /**
   *
   * @type {PaymentMethodsMetadataSofort}
   * @memberof PaymentMethodsMetadata
   */
  sofort?: PaymentMethodsMetadataSofort;
  /**
   *
   * @type {PaymentMethodsMetadataTrustly}
   * @memberof PaymentMethodsMetadata
   */
  trustly?: PaymentMethodsMetadataTrustly;
  /**
   *
   * @type {PaymentMethodsMetadataSepa}
   * @memberof PaymentMethodsMetadata
   */
  sepa?: PaymentMethodsMetadataSepa;
  /**
   *
   * @type {PaymentMethodsMetadataKlarna}
   * @memberof PaymentMethodsMetadata
   */
  klarna?: PaymentMethodsMetadataKlarna;
  /**
   *
   * @type {PaymentMethodsMetadataGiropay}
   * @memberof PaymentMethodsMetadata
   */
  giropay?: PaymentMethodsMetadataGiropay;
  /**
   *
   * @type {PaymentMethodsMetadataGooglePay}
   * @memberof PaymentMethodsMetadata
   */
  googlePay?: PaymentMethodsMetadataGooglePay;
  /**
   *
   * @type {PaymentMethodsMetadataApplePay}
   * @memberof PaymentMethodsMetadata
   */
  applePay?: PaymentMethodsMetadataApplePay;
  /**
   *
   * @type {PaymentMethodsMetadataClickToPay}
   * @memberof PaymentMethodsMetadata
   */
  clickToPay?: PaymentMethodsMetadataClickToPay;
}
