/* tslint:disable */
/* eslint-disable */
/**
 * MONEI API v1
 * The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.
 *
 * The version of the OpenAPI document: 1.12.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SubscriptionUpdatePreview
 */
export interface SubscriptionUpdatePreview {
  /**
   * Unused time that would be credited at the current price, in the smallest currency unit.
   * @type {number}
   * @memberof SubscriptionUpdatePreview
   */
  credit: number;
  /**
   * Time that would be charged at the new price, in the smallest currency unit. An interval change charges the full new price rather than a fraction of it.
   * @type {number}
   * @memberof SubscriptionUpdatePreview
   */
  charge: number;
  /**
   * The computed difference, `charge` minus `credit`. This is the amount that would move, in full: a refund the period\'s funding cannot cover is rejected rather than reduced, so a preview that returns a settlement returns the whole of it.
   * @type {number}
   * @memberof SubscriptionUpdatePreview
   */
  net: number;
  /**
   * Whether the difference would be charged, refunded, or neither. `none` means the difference rounds to zero and no money moves.
   * @type {string}
   * @memberof SubscriptionUpdatePreview
   */
  direction: SubscriptionUpdatePreviewDirectionEnum;
  /**
   * Always `false`. A refund is now either covered in full or the change is rejected, so there is no partial refund for this to report. Do not branch on it.
   * @type {boolean}
   * @memberof SubscriptionUpdatePreview
   * @deprecated
   */
  refundCapped: boolean;
  /**
   * The date the change would take effect.
   * @type {number}
   * @memberof SubscriptionUpdatePreview
   */
  effectiveAt: number;
  /**
   * The end date of the current subscription period. Measured in seconds since the Unix epoch.
   * @type {number}
   * @memberof SubscriptionUpdatePreview
   */
  currentPeriodEnd: number;
  /**
   * The end of the billing period the change would start. Present only when the change resets the period: an `interval` or `intervalCount` change, which restarts it from now, or a `nextPaymentAt` change, which moves the end to the new date.
   * @type {number}
   * @memberof SubscriptionUpdatePreview
   */
  newPeriodEnd?: number;
  /**
   * When the next payment would be taken. Present on the same changes as `newPeriodEnd`, and equal to it.
   * @type {number}
   * @memberof SubscriptionUpdatePreview
   */
  nextPaymentAt?: number;
}

export const SubscriptionUpdatePreviewDirectionEnum = {
  CHARGE: "charge",
  REFUND: "refund",
  NONE: "none",
} as const;

export type SubscriptionUpdatePreviewDirectionEnum =
  (typeof SubscriptionUpdatePreviewDirectionEnum)[keyof typeof SubscriptionUpdatePreviewDirectionEnum];
