/* tslint:disable */
/* eslint-disable */
/**
 * MONEI API v1
 * The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.
 *
 * The version of the OpenAPI document: 1.12.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * What the most recent prorated change settled. Present only after a prorated change.
 * @export
 * @interface SubscriptionLastProration
 */
export interface SubscriptionLastProration {
  /**
   * Unused time credited at the previous price, in the smallest currency unit.
   * @type {number}
   * @memberof SubscriptionLastProration
   */
  credit?: number;
  /**
   * Time charged at the new price, in the smallest currency unit. An interval change charges the full new price rather than a fraction of it.
   * @type {number}
   * @memberof SubscriptionLastProration
   */
  charge?: number;
  /**
   * The settled difference, `charge` minus `credit`. A positive value was charged to the saved payment method. A negative value was refunded.
   * @type {number}
   * @memberof SubscriptionLastProration
   */
  net?: number;
  /**
   * The payment that funds the current period on top of its renewal, and the first source a later refund draws on. Set to the new payment when a prorated change charges. A change that refunds or moves no money keeps whichever payment an earlier prorated charge in this period created, since that money is still what funds the period. Absent when no prorated charge has funded the current period.
   * @type {string}
   * @memberof SubscriptionLastProration
   */
  paymentId?: string;
}
