/* tslint:disable */
/* eslint-disable */
/**
 * MONEI API v1
 * The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.
 *
 * The version of the OpenAPI document: 1.12.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PaymentBillingDetails } from "./payment-billing-details";
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentShippingDetails } from "./payment-shipping-details";

/**
 * Only the fields you send are changed. Omitted fields keep their current value.
 * @export
 * @interface UpdateCustomerRequest
 */
export interface UpdateCustomerRequest {
  /**
   * The customer\'s email address.
   * @type {string}
   * @memberof UpdateCustomerRequest
   */
  email?: string;
  /**
   * The customer\'s full name or business name.
   * @type {string}
   * @memberof UpdateCustomerRequest
   */
  name?: string;
  /**
   * The customer\'s phone number in E.164 format.
   * @type {string}
   * @memberof UpdateCustomerRequest
   */
  phone?: string;
  /**
   *
   * @type {PaymentBillingDetails}
   * @memberof UpdateCustomerRequest
   */
  billingDetails?: PaymentBillingDetails;
  /**
   *
   * @type {PaymentShippingDetails}
   * @memberof UpdateCustomerRequest
   */
  shippingDetails?: PaymentShippingDetails;
  /**
   * A set of key-value pairs that you can attach to a resource. This can be useful for storing additional information about the resource in a structured format.
   * @type {object}
   * @memberof UpdateCustomerRequest
   */
  metadata?: object;
  /**
   * The payment method charged when a payment sets `useDefaultPaymentMethod`.  MONEI fills this only while it is empty: the first reusable payment method the customer saves becomes the default, and a value you set here is kept. Deleting that payment method clears the field, so the next reusable one the customer saves becomes the new default. It must be the ID of a payment method this customer already owns, and one that can be reused for future payments.
   * @type {string}
   * @memberof UpdateCustomerRequest
   */
  defaultTokenId?: string;
}
