/* tslint:disable */
/* eslint-disable */
/**
 * MONEI API v1
 * The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.
 *
 * The version of the OpenAPI document: 1.8.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "../axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { BadRequestError } from "../model";
// @ts-ignore
import type { CreatePosAuthTokenRequest } from "../model";
// @ts-ignore
import type { InternalServerError } from "../model";
// @ts-ignore
import type { PosAuthTokenCreate200Response } from "../model";
// @ts-ignore
import type { ServiceUnavailableError } from "../model";
// @ts-ignore
import type { UnauthorizedError } from "../model";
/**
 * POSAuthTokenApi - axios parameter creator
 * @export
 */
export const POSAuthTokenApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Generates an RS256-signed JWT token for POS terminal authentication.  Use this endpoint to create an auth token that a POS terminal (via MONEI Pay) can use to process payments. This is designed for app-to-app flows where your backend generates the token and passes it to the MONEI Pay app running on a POS device.  `pointOfSaleId` is optional — when provided, it is included in the JWT payload as `pos_id` and `device_id`, allowing you to associate payments with a specific terminal. `storeId` is also optional — included as `store_id` when provided. If `pointOfSaleId` is omitted, the system generates a `device_id` automatically.  The token is valid for 24 hours.
     * @summary Create POS Auth Token
     * @param {CreatePosAuthTokenRequest} createPosAuthTokenRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create: async (
      createPosAuthTokenRequest: CreatePosAuthTokenRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createPosAuthTokenRequest' is not null or undefined
      assertParamExists("create", "createPosAuthTokenRequest", createPosAuthTokenRequest);
      const localVarPath = `/pos/auth-token`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "POST", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication APIKey required
      await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createPosAuthTokenRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * POSAuthTokenApi - functional programming interface
 * @export
 */
export const POSAuthTokenApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = POSAuthTokenApiAxiosParamCreator(configuration);
  return {
    /**
     * Generates an RS256-signed JWT token for POS terminal authentication.  Use this endpoint to create an auth token that a POS terminal (via MONEI Pay) can use to process payments. This is designed for app-to-app flows where your backend generates the token and passes it to the MONEI Pay app running on a POS device.  `pointOfSaleId` is optional — when provided, it is included in the JWT payload as `pos_id` and `device_id`, allowing you to associate payments with a specific terminal. `storeId` is also optional — included as `store_id` when provided. If `pointOfSaleId` is omitted, the system generates a `device_id` automatically.  The token is valid for 24 hours.
     * @summary Create POS Auth Token
     * @param {CreatePosAuthTokenRequest} createPosAuthTokenRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async create(
      createPosAuthTokenRequest: CreatePosAuthTokenRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PosAuthTokenCreate200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.create(
        createPosAuthTokenRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["POSAuthTokenApi.create"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * POSAuthTokenApi - factory interface
 * @export
 */
export const POSAuthTokenApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = POSAuthTokenApiFp(configuration);
  return {
    /**
     * Generates an RS256-signed JWT token for POS terminal authentication.  Use this endpoint to create an auth token that a POS terminal (via MONEI Pay) can use to process payments. This is designed for app-to-app flows where your backend generates the token and passes it to the MONEI Pay app running on a POS device.  `pointOfSaleId` is optional — when provided, it is included in the JWT payload as `pos_id` and `device_id`, allowing you to associate payments with a specific terminal. `storeId` is also optional — included as `store_id` when provided. If `pointOfSaleId` is omitted, the system generates a `device_id` automatically.  The token is valid for 24 hours.
     * @summary Create POS Auth Token
     * @param {CreatePosAuthTokenRequest} createPosAuthTokenRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    create(
      createPosAuthTokenRequest: CreatePosAuthTokenRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PosAuthTokenCreate200Response> {
      return localVarFp
        .create(createPosAuthTokenRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * POSAuthTokenApi - object-oriented interface
 * @export
 * @class POSAuthTokenApi
 * @extends {BaseAPI}
 */
export class POSAuthTokenApi extends BaseAPI {
  /**
   * Generates an RS256-signed JWT token for POS terminal authentication.  Use this endpoint to create an auth token that a POS terminal (via MONEI Pay) can use to process payments. This is designed for app-to-app flows where your backend generates the token and passes it to the MONEI Pay app running on a POS device.  `pointOfSaleId` is optional — when provided, it is included in the JWT payload as `pos_id` and `device_id`, allowing you to associate payments with a specific terminal. `storeId` is also optional — included as `store_id` when provided. If `pointOfSaleId` is omitted, the system generates a `device_id` automatically.  The token is valid for 24 hours.
   * @summary Create POS Auth Token
   * @param {CreatePosAuthTokenRequest} createPosAuthTokenRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof POSAuthTokenApi
   */
  public create(
    createPosAuthTokenRequest: CreatePosAuthTokenRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return POSAuthTokenApiFp(this.configuration)
      .create(createPosAuthTokenRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
